networks:
  traefik:
    external: true
  backend_oc:

volumes:
  db_data:
  opencart_data:

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_oc
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 20

  opencart:
    build:
      context: ./docker/opencart
      args:
        OPENCART_VERSION: ${OPENCART_VERSION:-4.1.0.3}
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOSTNAME: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      OC_ADMIN_USERNAME: ${OC_ADMIN_USER}
      OC_ADMIN_PASSWORD: ${OC_ADMIN_PASSWORD}
      OC_ADMIN_EMAIL: ${OC_ADMIN_EMAIL}
      HTTP_SERVER: https://${OC_DOMAIN}/
    volumes:
      - opencart_data:/var/www/html
    networks:
      - traefik
      - backend_oc
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.oc.loadbalancer.server.port=80"
      - "traefik.http.routers.oc.rule=Host(`${OC_DOMAIN}`)"
      - "traefik.http.routers.oc.entrypoints=web"
      - "traefik.http.middlewares.oc-https.redirectscheme.scheme=https"
      - "traefik.http.routers.oc.middlewares=oc-https"
      - "traefik.http.routers.oc-secured.rule=Host(`${OC_DOMAIN}`)"
      - "traefik.http.routers.oc-secured.entrypoints=web-secure"
      - "traefik.http.routers.oc-secured.tls=true"
      - "traefik.http.routers.oc-secured.tls.certresolver=myhttpchallenge"
